#' Compute Area Under the P-score Curve (AUPC) from \code{pscore_civs} output
#'
#' @description
#' Computes the Area Under the P-score Curve (AUPC) for each treatment, using the
#' P-scores and CIV combinations generated by \code{pscore_civs}. AUPC is
#' interpreted as the average probability that a treatment beats all others,
#' averaged over the specified grid of CIVs.
#'
#' @param x A \code{pscore_civs} object (output of \code{pscore_civs} function).
#' @param excel Logical. If \code{TRUE}, the results are exported to an Excel
#'   file. Default is \code{FALSE}.
#'
#' @details
#' AUPC is computed from the P-scores in a \code{pscore_civs} object and used
#' to rank treatments over the specified CIV grid. If \code{excel = TRUE},
#' results are exported to an Excel file in the working directory.
#'
#' @return A data frame with the following columns:
#' \describe{
#'   \item{AUPC}{Average probability that the treatment beats all others over
#'     the considered CIV combinations.}
#'   \item{Treatment}{Treatment labels.}
#'   \item{ranking}{Ranking based on AUPC; highest AUPC ranked 1.}
#' }
#'
#' @export
#'
#' @examples
#' \dontrun{
#' data("efficacy")
#' out_eff <- pscore_civs(
#'   list(efficacy),
#'   CIVs = list(seq(0, 0.5, length.out = 50)),
#'   correlation = NULL,
#'   type = "H"
#' )
#' aupc(out_eff)
#' }
aupc <- function(x,excel=FALSE) {

  df <- x$pscores
  civs <- x$CIVs

  labels <- colnames(df)

  # check
  if(nrow(df) != nrow(civs)) {

    stop("Number of rows of df and civs must be equal")

  } else if(nrow(civs) < 2) {

    stop("More than one combo of CIVs must be considered to calculate the area")

  }

  # Drop the rows which only have one CIV

  nval <- apply(civs, 2, function(x) length(unique(x)))

  civs <- as.matrix(civs[,which(nval>1)])

  hs <- apply(civs, 2, function(x) (max(x)-min(x))/length(unique(x)))

  auc <- apply(df, 2, function(x, h) sum(x*prod(h)), h = hs)

  names(auc) <- labels

  ranking <- rank(-auc)

  res<-(data.frame(AUPC = auc, Treatment = labels, ranking = ranking)) # average probability that it beats all other treatments, averaged over the CIVs

  if (isTRUE(excel)) {
    filename <- paste0("aupc_", format(Sys.Date(), "%Y%m%d"), ".xlsx")
    writexl::write_xlsx(list("AUPC Results" = res), path = filename)
    message("Results saved to: ", filename)
  }

  return(res)
}
